# Generated by Django 5.2.17 on 2026-09-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
